
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab16.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Course
{

    public Course()
    {

        this.CourseGrade = new HashSet<CourseGrade>();

        this.Person = new HashSet<Person>();

    }


    public int CourseID { get; set; }

    public string Title { get; set; }

    public int Credits { get; set; }

    public int DepartmentID { get; set; }



    public virtual Department Department { get; set; }

    public virtual ICollection<CourseGrade> CourseGrade { get; set; }

    public virtual OnlineCourse OnlineCourse { get; set; }

    public virtual OnsiteCourse OnsiteCourse { get; set; }

    public virtual ICollection<Person> Person { get; set; }

}

}
