
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab16.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Department
{

    public Department()
    {

        this.Course = new HashSet<Course>();

    }


    public int DepartmentID { get; set; }

    public string Name { get; set; }

    public decimal Budget { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<int> Administrator { get; set; }



    public virtual ICollection<Course> Course { get; set; }

}

}
