
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Lab16.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Person
{

    public Person()
    {

        this.CourseGrade = new HashSet<CourseGrade>();

        this.Course = new HashSet<Course>();

    }


    public int PersonID { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public Nullable<System.DateTime> HireDate { get; set; }

    public Nullable<System.DateTime> EnrollmentDate { get; set; }



    public virtual ICollection<CourseGrade> CourseGrade { get; set; }

    public virtual OfficeAssignment OfficeAssignment { get; set; }

    public virtual ICollection<Course> Course { get; set; }

}

}
